
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_DRAWER_OPTION = "SET_DRAWER_OPTION";
export const SET_MAIN_DISPLAY = "SET_MAIN_DISPLAY";
export const SET_REACT_LIST = "SET_REACT_LIST";
export const SET_DB_LIST = "SET_DB_LIST";
export const SET_NODE_LIST = "SET_NODE_LIST";
export const SET_SIDE_BUTTONS = "SET_SIDE_BUTTONS";